# Generated by Django 5.2.17 on 2026-09-02 09:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сесії')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('converted', 'Оформлений'), ('abandoned', 'Покинутий')], default='active', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'db_table': 'commerce_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Позиція кошика',
                'verbose_name_plural': 'Позиції кошика',
                'db_table': 'commerce_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('awaiting_payment', 'Очікує оплату'), ('paid', 'Оплачене'), ('processing', 'Обробка'), ('shipped', 'Відправлене'), ('done', 'Виконане'), ('cancelled', 'Скасоване')], default='new', max_length=32, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Імʼя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('subtotal_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Підсумок, грн')),
                ('shipping_uah', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доставка, грн')),
                ('total_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Разом, грн')),
                ('payment_method', models.CharField(max_length=32, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('refunded', 'Повернення')], default='pending', max_length=32, verbose_name='Статус оплати')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('shipping_method', models.CharField(choices=[('np_warehouse', 'НП відділення'), ('np_courier', 'НП курʼєр'), ('pickup_salon', 'Самовивіз із салону')], max_length=32, verbose_name='Спосіб доставки')),
                ('np_city_ref', models.CharField(blank=True, max_length=64, null=True, verbose_name='НП city ref')),
                ('np_city_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='НП місто')),
                ('np_warehouse_ref', models.CharField(blank=True, max_length=64, null=True, verbose_name='НП warehouse ref')),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='НП відділення')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Адреса доставки')),
                ('pickup_salon_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Салон')),
                ('pickup_salon_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адреса салону')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'commerce_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_snapshot', models.CharField(max_length=64, verbose_name='SKU snapshot')),
                ('name_snapshot', models.CharField(max_length=255, verbose_name='Назва snapshot')),
                ('unit_price_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна, грн')),
                ('qty', models.PositiveIntegerField(verbose_name='Кількість')),
                ('line_total_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума рядка, грн')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'db_table': 'commerce_order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Зі статусу')),
                ('to_status', models.CharField(max_length=32, verbose_name='До статусу')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Нотатка')),
            ],
            options={
                'verbose_name': 'Лог статусу замовлення',
                'verbose_name_plural': 'Логи статусів замовлень',
                'db_table': 'commerce_order_status_log',
                'ordering': ['created_at'],
            },
        ),
    ]
