# Generated by Django 5.2.17 on 2026-09-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(max_length=255, upload_to='banners/%Y/%m/', verbose_name='Зображення')),
                ('link_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Посилання')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'db_table': 'content_banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.CharField(blank=True, max_length=512, null=True, verbose_name='Короткий опис')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cover_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/%Y/%m/', verbose_name='Обкладинка')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Запис блогу',
                'verbose_name_plural': 'Блог',
                'db_table': 'content_blog_post',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'content_faq_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'db_table': 'content_page',
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компанія')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контакт')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Місто')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('done', 'Оброблена'), ('rejected', 'Відхилена')], default='new', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка партнера',
                'verbose_name_plural': 'Заявки партнерів',
                'db_table': 'content_partner_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Країна')),
                ('city', models.CharField(max_length=128, verbose_name='Місто')),
                ('address', models.CharField(max_length=512, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Години роботи')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салони',
                'db_table': 'content_salon',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrunkShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Місто')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місце')),
                ('starts_at', models.DateTimeField(verbose_name='Початок')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Trunk-show',
                'verbose_name_plural': 'Trunk-show',
                'db_table': 'content_trunk_show',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='BrideGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(max_length=255, upload_to='brides/%Y/%m/', verbose_name='Зображення')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bride_gallery_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Наречена',
                'verbose_name_plural': 'Наречені',
                'db_table': 'content_bride_gallery_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('site_name', models.CharField(max_length=255, verbose_name='Назва сайту')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('contacts_json', models.JSONField(default=dict, verbose_name='Контакти')),
                ('robots_txt', models.TextField(blank=True, null=True, verbose_name='robots.txt')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
                'db_table': 'content_site_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='content_site_settings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('author_name', models.CharField(max_length=255, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'db_table': 'content_review',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='content_review_rating_1_5')],
            },
        ),
    ]
