# Generated by Django 5.2.17 on 2026-09-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_trunkshow_verbose_podii'),
    ]

    operations = [
        migrations.AddField(
            model_name='trunkshow',
            name='home_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.homepage', verbose_name='Головна'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='events_is_visible',
            field=models.BooleanField(default=True, help_text='Вимкніть, щоб сховати всю секцію. Картки нижче не видаляються.', verbose_name='Показувати блок подій'),
        ),
        migrations.AlterField(
            model_name='trunkshow',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва'),
        ),
    ]
