CATEGORIES = [
    {
        'slug': 'wedding',
        'name': 'Весільні сукні',
        'parent': None,
        'sort_order': 10,
        'description': 'Колекція весільних суконь ательє Varvarova: класика, романтика та сучасний крій.',
    },
    {
        'slug': 'evening',
        'name': 'Вечірні сукні',
        'parent': None,
        'sort_order': 20,
        'description': 'Вечірні та кутюрні сукні для виходу, зйомки й урочистостей.',
    },
    {
        'slug': 'wedding-a-line',
        'name': 'A-силует',
        'parent': 'wedding',
        'sort_order': 11,
        'description': 'Легкий розкльошений силует, зручний для церемонії та банкету.',
    },
    {
        'slug': 'wedding-mermaid',
        'name': 'Русалка',
        'parent': 'wedding',
        'sort_order': 12,
        'description': 'Облеглий крій із розкльошеним низом.',
    },
    {
        'slug': 'wedding-ballgown',
        'name': 'Пишні',
        'parent': 'wedding',
        'sort_order': 13,
        'description': 'Обʼємна спідниця та виразна талія.',
    },
    {
        'slug': 'evening-couture',
        'name': 'Couture',
        'parent': 'evening',
        'sort_order': 21,
        'description': 'Сукні ручної роботи з розшивом і складним кроєм.',
    },
    {
        'slug': 'evening-bridesmaid',
        'name': 'Дружки',
        'parent': 'evening',
        'sort_order': 22,
        'description': 'Елегантні сукні для дружок у палітрі колекції.',
    },
    {
        'slug': 'accessories',
        'name': 'Аксесуари',
        'parent': None,
        'sort_order': 30,
        'description': 'Фати, рукавички, кейпи, пояси та знімні елементи до весільного образу.',
    },
    {
        'slug': 'accessories-veils',
        'name': 'Фати',
        'parent': 'accessories',
        'sort_order': 31,
        'description': 'Весільні фати різної довжини та декору.',
    },
    {
        'slug': 'accessories-gloves',
        'name': 'Рукавички',
        'parent': 'accessories',
        'sort_order': 32,
        'description': 'Довгі, короткі, прозорі та мереживні рукавички.',
    },
    {
        'slug': 'accessories-capes',
        'name': 'Кейпи та накидки',
        'parent': 'accessories',
        'sort_order': 33,
        'description': 'Кейпи й накидки до весільних та вечірніх суконь.',
    },
    {
        'slug': 'accessories-belts',
        'name': 'Пояси',
        'parent': 'accessories',
        'sort_order': 34,
        'description': 'Пояси до весільних суконь.',
    },
    {
        'slug': 'accessories-detachable',
        'name': 'Знімні елементи',
        'parent': 'accessories',
        'sort_order': 35,
        'description': 'Знімні бретелі, рукави та плечові елементи.',
    },
    {
        'slug': 'lingerie',
        'name': 'Весільна білизна',
        'parent': None,
        'sort_order': 40,
        'description': 'Весільна білизна: бюстгальтери, трусики, підвʼязки, панчохи та боді.',
    },
    {
        'slug': 'lingerie-bras',
        'name': 'Бюстгальтери',
        'parent': 'lingerie',
        'sort_order': 41,
        'description': 'Бюстгальтери до весільного образу.',
    },
    {
        'slug': 'lingerie-briefs',
        'name': 'Трусики',
        'parent': 'lingerie',
        'sort_order': 42,
        'description': 'Весільні трусики.',
    },
    {
        'slug': 'lingerie-garters',
        'name': 'Підвʼязки',
        'parent': 'lingerie',
        'sort_order': 43,
        'description': 'Підвʼязки до весільного образу.',
    },
    {
        'slug': 'lingerie-stockings',
        'name': 'Панчохи',
        'parent': 'lingerie',
        'sort_order': 44,
        'description': 'Весільні панчохи.',
    },
    {
        'slug': 'lingerie-bodysuits',
        'name': 'Боді',
        'parent': 'lingerie',
        'sort_order': 45,
        'description': 'Весільні боді.',
    },
]

ATTRIBUTES = [
    ('silhouette', 'Силует', 10, (
        ('a-line', 'A-силует'),
        ('mermaid', 'Русалка'),
        ('ballgown', 'Пишний'),
        ('sheath', 'Футляр'),
        ('empire', 'Ампір'),
    )),
    ('color', 'Колір', 20, (
        ('ivory', 'Айворі'),
        ('white', 'Білий'),
        ('champagne', 'Шампань'),
        ('blush', 'Пудра'),
        ('black', 'Чорний'),
        ('red', 'Бордо'),
        ('emerald', 'Смарагд'),
        ('navy', 'Синій'),
    )),
    ('fabric', 'Тканина', 30, (
        ('mikado', 'Мікадо'),
        ('satin', 'Атлас'),
        ('lace', 'Мереживо'),
        ('tulle', 'Фатин'),
        ('crepe', 'Креп'),
        ('organza', 'Органза'),
    )),
    ('decor', 'Декор', 40, (
        ('embroidery', 'Вишивка'),
        ('beads', 'Бісер'),
        ('pearls', 'Перли'),
        ('applique', 'Аплікація'),
        ('minimal', 'Мінімалізм'),
    )),
    ('style', 'Стиль', 50, (
        ('classic', 'Класика'),
        ('romantic', 'Романтика'),
        ('modern', 'Сучасний'),
        ('boho', 'Богемний'),
    )),
    ('neckline', 'Виріз', 60, (
        ('strapless', 'Без бретелей'),
        ('sweetheart', 'Серце'),
        ('v-neck', 'V-виріз'),
        ('boat', 'Човник'),
        ('illusion', 'Ілюзія'),
    )),
    ('length', 'Довжина', 70, (
        ('floor', 'В підлогу'),
        ('midi', 'Міді'),
        ('mini', 'Міні'),
        ('chapel-train', 'Шлейф chapel'),
        ('cathedral-train', 'Шлейф cathedral'),
    )),
]

# sku, slug, name, category, price, stock, featured, tone, attrs
PRODUCTS = [
    ('VV-W-001', 'aurelia', 'Aurelia', 'wedding-a-line', '42800', 4, True, 'ivory',
     {'silhouette': 'a-line', 'color': 'ivory', 'fabric': 'lace', 'decor': 'applique',
      'style': 'romantic', 'neckline': 'illusion', 'length': 'chapel-train'}),
    ('VV-W-002', 'celeste', 'Celeste', 'wedding-mermaid', '51200', 3, True, 'white',
     {'silhouette': 'mermaid', 'color': 'white', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'v-neck', 'length': 'chapel-train'}),
    ('VV-W-003', 'isadora', 'Isadora', 'wedding-ballgown', '58900', 2, True, 'champagne',
     {'silhouette': 'ballgown', 'color': 'champagne', 'fabric': 'tulle', 'decor': 'embroidery',
      'style': 'romantic', 'neckline': 'sweetheart', 'length': 'cathedral-train'}),
    ('VV-W-004', 'elara', 'Elara', 'wedding-a-line', '39600', 5, True, 'blush',
     {'silhouette': 'a-line', 'color': 'blush', 'fabric': 'organza', 'decor': 'pearls',
      'style': 'romantic', 'neckline': 'boat', 'length': 'floor'}),
    ('VV-W-005', 'seraphine', 'Seraphine', 'wedding-mermaid', '54800', 2, True, 'ivory',
     {'silhouette': 'mermaid', 'color': 'ivory', 'fabric': 'satin', 'decor': 'beads',
      'style': 'classic', 'neckline': 'strapless', 'length': 'chapel-train'}),
    ('VV-W-006', 'valeria', 'Valeria', 'wedding-a-line', '36400', 6, True, 'white',
     {'silhouette': 'a-line', 'color': 'white', 'fabric': 'mikado', 'decor': 'minimal',
      'style': 'classic', 'neckline': 'boat', 'length': 'floor'}),
    ('VV-W-007', 'odette', 'Odette', 'wedding-ballgown', '62400', 1, True, 'ivory',
     {'silhouette': 'ballgown', 'color': 'ivory', 'fabric': 'tulle', 'decor': 'applique',
      'style': 'classic', 'neckline': 'illusion', 'length': 'cathedral-train'}),
    ('VV-W-008', 'linnea', 'Linnea', 'wedding-a-line', '33800', 4, True, 'ivory',
     {'silhouette': 'sheath', 'color': 'ivory', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'v-neck', 'length': 'floor'}),
    ('VV-W-009', 'mirabelle', 'Mirabelle', 'wedding-a-line', '41200', 3, False, 'champagne',
     {'silhouette': 'a-line', 'color': 'champagne', 'fabric': 'lace', 'decor': 'embroidery',
      'style': 'boho', 'neckline': 'illusion', 'length': 'chapel-train'}),
    ('VV-W-010', 'solene', 'Solene', 'wedding-mermaid', '47600', 2, False, 'white',
     {'silhouette': 'mermaid', 'color': 'white', 'fabric': 'satin', 'decor': 'pearls',
      'style': 'classic', 'neckline': 'sweetheart', 'length': 'floor'}),
    ('VV-W-011', 'camille', 'Camille', 'wedding-ballgown', '45500', 2, False, 'blush',
     {'silhouette': 'ballgown', 'color': 'blush', 'fabric': 'organza', 'decor': 'beads',
      'style': 'romantic', 'neckline': 'strapless', 'length': 'chapel-train'}),
    ('VV-W-012', 'noelle', 'Noelle', 'wedding-a-line', '29800', 7, False, 'ivory',
     {'silhouette': 'a-line', 'color': 'ivory', 'fabric': 'tulle', 'decor': 'minimal',
      'style': 'classic', 'neckline': 'sweetheart', 'length': 'floor'}),
    ('VV-W-013', 'evangeline', 'Evangeline', 'wedding-mermaid', '53200', 1, False, 'ivory',
     {'silhouette': 'mermaid', 'color': 'ivory', 'fabric': 'lace', 'decor': 'applique',
      'style': 'romantic', 'neckline': 'illusion', 'length': 'cathedral-train'}),
    ('VV-W-014', 'paloma', 'Paloma', 'wedding-a-line', '27600', 5, False, 'champagne',
     {'silhouette': 'empire', 'color': 'champagne', 'fabric': 'organza',
      'decor': 'embroidery', 'style': 'boho', 'neckline': 'v-neck', 'length': 'floor'}),
    ('VV-W-015', 'thea', 'Thea', 'wedding-a-line', '31900', 0, False, 'white',
     {'silhouette': 'sheath', 'color': 'white', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'boat', 'length': 'midi'}),
    ('VV-W-016', 'bianca', 'Bianca', 'wedding-ballgown', '49800', 3, False, 'ivory',
     {'silhouette': 'ballgown', 'color': 'ivory', 'fabric': 'mikado', 'decor': 'pearls',
      'style': 'classic', 'neckline': 'strapless', 'length': 'chapel-train'}),
    ('VV-E-001', 'nocturne', 'Nocturne', 'evening', '18600', 4, False, 'black',
     {'silhouette': 'sheath', 'color': 'black', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'v-neck', 'length': 'floor'}),
    ('VV-E-002', 'rubina', 'Rubina', 'evening', '21400', 3, False, 'red',
     {'silhouette': 'mermaid', 'color': 'red', 'fabric': 'satin', 'decor': 'beads',
      'style': 'classic', 'neckline': 'sweetheart', 'length': 'floor'}),
    ('VV-E-003', 'verde', 'Verde', 'evening', '19800', 3, False, 'emerald',
     {'silhouette': 'a-line', 'color': 'emerald', 'fabric': 'mikado', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'boat', 'length': 'floor'}),
    ('VV-E-004', 'marina', 'Marina', 'evening', '16400', 5, False, 'navy',
     {'silhouette': 'sheath', 'color': 'navy', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'classic', 'neckline': 'v-neck', 'length': 'midi'}),
    ('VV-E-005', 'onyx', 'Onyx', 'evening', '24200', 2, False, 'black',
     {'silhouette': 'mermaid', 'color': 'black', 'fabric': 'satin', 'decor': 'embroidery',
      'style': 'classic', 'neckline': 'strapless', 'length': 'floor'}),
    ('VV-E-006', 'ambra', 'Ambra', 'evening', '17800', 4, False, 'champagne',
     {'silhouette': 'a-line', 'color': 'champagne', 'fabric': 'organza', 'decor': 'pearls',
      'style': 'romantic', 'neckline': 'illusion', 'length': 'floor'}),
    ('VV-C-001', 'atelier-noir', 'Atelier Noir', 'evening-couture', '48600', 1, False, 'black',
     {'silhouette': 'sheath', 'color': 'black', 'fabric': 'crepe', 'decor': 'beads',
      'style': 'modern', 'neckline': 'illusion', 'length': 'floor'}),
    ('VV-C-002', 'atelier-ivoire', 'Atelier Ivoire', 'evening-couture', '52400', 1, False, 'ivory',
     {'silhouette': 'mermaid', 'color': 'ivory', 'fabric': 'lace', 'decor': 'embroidery',
      'style': 'classic', 'neckline': 'sweetheart', 'length': 'chapel-train'}),
    ('VV-C-003', 'atelier-emeraude', 'Atelier Emeraude', 'evening-couture', '45800', 2, False, 'emerald',
     {'silhouette': 'a-line', 'color': 'emerald', 'fabric': 'mikado', 'decor': 'applique',
      'style': 'modern', 'neckline': 'boat', 'length': 'floor'}),
    ('VV-C-004', 'atelier-rose', 'Atelier Rose', 'evening-couture', '41200', 2, False, 'blush',
     {'silhouette': 'empire', 'color': 'blush', 'fabric': 'tulle', 'decor': 'pearls',
      'style': 'romantic', 'neckline': 'illusion', 'length': 'floor'}),
    ('VV-B-001', 'rosa', 'Rosa', 'evening-bridesmaid', '9800', 8, False, 'blush',
     {'silhouette': 'a-line', 'color': 'blush', 'fabric': 'organza',
      'decor': 'minimal', 'style': 'romantic', 'neckline': 'sweetheart', 'length': 'midi'}),
    ('VV-B-002', 'amber-maid', 'Amber', 'evening-bridesmaid', '10400', 6, False, 'champagne',
     {'silhouette': 'empire', 'color': 'champagne', 'fabric': 'crepe', 'decor': 'minimal',
      'style': 'classic', 'neckline': 'v-neck', 'length': 'midi'}),
    ('VV-B-003', 'ink', 'Ink', 'evening-bridesmaid', '11200', 5, False, 'navy',
     {'silhouette': 'sheath', 'color': 'navy', 'fabric': 'satin', 'decor': 'minimal',
      'style': 'modern', 'neckline': 'boat', 'length': 'floor'}),
    ('VV-B-004', 'pearl-maid', 'Pearl', 'evening-bridesmaid', '8900', 7, False, 'ivory',
     {'silhouette': 'a-line', 'color': 'ivory', 'fabric': 'tulle', 'decor': 'pearls',
      'style': 'romantic', 'neckline': 'sweetheart', 'length': 'midi'}),
]
